nome = str(input('Digite seu nome COMPLETO: '))
maiusculo = nome.upper() 
minusculo = nome.lower()
letras = (len(nome.strip()))
p1nome = (nome.split()[0])
letras2 = (len(p1nome.strip()))
print('Seu nome em maiúsculo fica assim: {}'.format(maiusculo))
print('Em minúsculo ele fica assim: {}'.format(minusculo))
print('Seu nome tem {} letras.'.format(letras))
print('Seu primeiro nome é {} e ele tem {} letras.'.format(p1nome, letras2))
