num = str(input('Digite um número de 0 a 9999: '))
num2 = (' '.join(num).split())
u = (num2 [3])
d = (num2 [2])
c = (num2 [1])
um = (num2 [0])
print('Unidade: {}'.format(u))
print('Dezena: {}'.format(d))
print('Centena: {}'.format(c))
print('Unidade de milhar: {}'.format(um))
